### ISSUE TITLE
[MY] S.L.A.M

### ISSUE THREAD

**Issue by vindowvipre** [Bauumm/OpenHexagonLevelConverter#10]
S.L.A.M was intended to be played with uncapped fps, and so the spirals in the ported version are much too tight. Maybe make the default virtual FPS higher? I worry other levels are getting similarly mauled

**Comment by Bauumm** [comment]
Well i have one issue with making the default fps larger, which is performance. Backwards compatability should not be exclusive to people with good pcs, so unless we somehow compromise (e. g. only updating the timeline more often like that) it would be bad. But even with that it would not work because then the timeline would not be synced with the events. So I really don't know where to draw the line here. Some benchmarks on different hardware could help.

**Comment by vindowvipre** [comment]
Fixed for SLAM, but the issue of FPS is still hard to answer
