### ISSUE TITLE
[IDFK] Fall of the Walls

### ISSUE THREAD

**Issue by vindowvipre** [Bauumm/OpenHexagonLevelConverter#12]
Due to an error from math.randomseed(), the port of Fall of the Walls in IDFK does not spawn any walls.

**Comment by Bauumm** [comment]
yes, because I still use the default math.random that the game defines there is no math.randomseed. This can be fixed in two ways:
1. reimplement math.random in lua.
2. check if that randomseed call is actually fixed, if it isn't it's probably ok to just delete/ignore it (by e.g. defining math.randomseed as doing nothing).

**Comment by Bauumm** [comment]
Should be fixed in the newest version but it may not be 100% the same since I'm using a different random generator.

**Comment by Bauumm** [comment]
Ok so after testing it turns out that probably due to stdlib implementations the windows build and the linux build of 1.92 have different rng with the same seed anyway, so I probably don't need to adjust my implementation.
